services:
  - type: web
    name: trmnl-fastapi
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "./start.sh"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: trmnl-db
          property: connectionString

databases:
  - name: trmnl-db
